name: "🟢 tekcit-frontend – Docker Build & GitOps Dispatch (nginx-client only)"

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: tekcit-frontend-${{ github.ref_name }}
  cancel-in-progress: true

env:
  SERVICE: fe-user                                      # GitOps가 인식하는 서비스명
  IMAGE:   ${{ secrets.DOCKER_USERNAME }}/nginx-client  # 레지스트리 이미지명
  DEVOPS_REPO: 3-mnms/gitops-repo

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      # ⛳️ 타입체크 없이 번들만 생성 (tsc 미실행)
      - name: Install deps
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Build (vite only, no typecheck)
        run: npx vite build

      - name: Verify dist exists
        run: |
          test -d dist || { echo "❌ dist not found"; exit 1; }
          ls -al dist | head -n 50

      # 🧩 빌드 산출물 전용 컨텍스트 생성 (.dockerignore 영향 회피)
      - name: Create CI build context (Dockerfile + default.conf + dist)
        run: |
          set -euo pipefail

          # 1) default.conf 준비: repo에 있으면 사용, 없으면 SPA 기본 생성
          if [ -f deploy/nginx.conf ]; then
            cp deploy/nginx.conf default.conf
          else
            printf '%s\n' \
              'server {' \
              '  listen 80;' \
              '  server_name _;' \
              '  root /usr/share/nginx/html;' \
              '  index index.html;' \
              '' \
              '  location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico)$ {' \
              '    try_files $uri =404;' \
              '    expires 7d;' \
              '    add_header Cache-Control "public, max-age=604800, immutable";' \
              '  }' \
              '' \
              '  location / {' \
              '    try_files $uri /index.html;' \
              '  }' \
              '' \
              '  location = /healthz {' \
              '    add_header Content-Type text/plain;' \
              '    return 200 "ok";' \
              '  }' \
              '}' > default.conf
          fi

          # 2) ci-context 생성 및 파일 복사
          rm -rf ci-context
          mkdir -p ci-context
          cp -r dist ci-context/dist
          cp default.conf ci-context/default.conf

          # 3) 컨텍스트용 Dockerfile 생성
          cat > ci-context/Dockerfile <<'DOCKER'
          FROM nginx:1.27-alpine
          COPY default.conf /etc/nginx/conf.d/default.conf
          COPY dist /usr/share/nginx/html
          EXPOSE 80
          CMD ["nginx","-g","daemon off;"]
          DOCKER

          echo "== ci-context =="
          ls -al ci-context
          echo "== ci-context/dist (head) =="
          ls -al ci-context/dist | head -n 30

      - name: ⏱️ Tag & Env
        run: |
          echo "TAG=v$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          if [ "${GITHUB_REF_NAME}" = "main" ]; then echo "ENV=prod" >> $GITHUB_ENV; else echo "ENV=develop" >> $GITHUB_ENV; fi

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=${{ env.TAG }}
            type=sha
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}

      - uses: docker/build-push-action@v5
        with:
          context: ./ci-context              # ← dist 포함된 전용 컨텍스트
          file: ./ci-context/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Dispatch to GitOps
        uses: peter-evans/repository-dispatch@v3
        with:
          token:  ${{ secrets.GH_PAT }}
          repository: ${{ env.DEVOPS_REPO }}
          event-type: image-updated
          client-payload: |
            {
              "service": "${{ env.SERVICE }}",
              "image":   "${{ env.IMAGE }}",
              "tag":     "${{ env.TAG }}",
              "env":     "${{ env.ENV }}"
            }